### ISSUE TITLE
quantification-type

### ISSUE THREAD

**Issue by GIOVANNI-75** [moritztng/llamars#1]
Hi, first I wanted to tell you that you did a very nice job.
And for the rest I had a question, I can't determine the quantification method used for the weights, I wanted to try with a Mixtral model that I had fine-tuned but I quickly saw that it was not not a type quantification (gguf/ggml) nor a torch classic backup

I tried the python script that is provided but it takes neither safetensors nor torch nor even (ggml/gguf)
the error is: ``` invalid load key, '\x00' ```

**Comment by Madd0g** [comment]
I'm a noob, what's the answer? what's the model input type?
